[package]
name = "rust_gui_trial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8.3"
resvg = "0.41.0"
tiny-skia = "0.11.4"
fontdb = "0.16.2"